#task_create_data_model
it-top-shambala/University_PD111 pull request #1
Opened 2022-06-28 15:07 UTC by anst-foto

2022-06-28 15:15 UTC, anst-foto commented
![](https://github.trello.services/images/mini-trello-icon.png) [#task_create_data_model](https://trello.com/c/R3xHzYiJ/2-taskcreatedatamodel)

2022-06-28 15:20 UTC, nazardyumin requested changes
Не внесены данные в файл README

2022-06-28 15:36 UTC, nazardyumin approved these changes
Спасибо!

2022-06-28 15:38 UTC, merged

2022-06-28 15:38 UTC, AnkushinAA reviewed
согласен

2022-07-04 06:08 UTC, GalinaRubo reviewed
All rights